//************************************************************
// See LICENSE for license details.
//
// Module: uv_rom_logic
//
// Designer: Owen
//
// Description:
//      ROM Logic for Boot.
//      This file was automatically generated by rom_gen.py
//      at 21:36:25, 2023/04/29.
//************************************************************

`timescale 1ns / 1ps

module uv_rom_logic
#(
    parameter ROM_AW = 10
)
(
    input                           clk,
    input                           rst_n,

    input  [ROM_AW-1:0]             rom_addr,
    output [63:0]                   rom_data
);

    localparam ROM_DP = 2;
    wire [31:0] rom_array [0:ROM_DP-1];
    wire [31:0] rom_data0;
    wire [31:0] rom_data1;
    wire [ROM_AW-1:0] rom_addr_add;

    assign rom_addr_add = rom_addr + 1'b1;
    assign rom_data0    = rom_addr < ROM_DP[ROM_AW-1:0] ? rom_array[rom_addr] : 32'h0;
    assign rom_data1    = rom_addr_add < ROM_DP[ROM_AW-1:0] ? rom_array[rom_addr_add] : 32'h0;
    assign rom_data     = {rom_data1, rom_data0};

    assign rom_array[0] = 32'h800002b7;
    assign rom_array[1] = 32'h00028067;

endmodule
