//************************************************************
// See LICENSE for license details.
//
// Module: uv_bus_fab_1x8
//
// Designer: Owen
//
// Description:
//      Bus fabric with 1 master port and 8 slave ports.
//      Generated by general bus fabric.
//************************************************************

`timescale 1ns / 1ps

module uv_bus_fab_1x8
#(
    parameter ALEN                  = 32,
    parameter DLEN                  = 32,
    parameter MLEN                  = DLEN / 8,
    parameter PIPE_STAGE            = 0,
    parameter SLV0_BASE_LSB         = 28,
    parameter SLV0_BASE_ADDR        = 4'h0,
    parameter SLV1_BASE_LSB         = 28,
    parameter SLV1_BASE_ADDR        = 4'h1,
    parameter SLV2_BASE_LSB         = 28,
    parameter SLV2_BASE_ADDR        = 4'h2,
    parameter SLV3_BASE_LSB         = 28,
    parameter SLV3_BASE_ADDR        = 4'h3,
    parameter SLV4_BASE_LSB         = 28,
    parameter SLV4_BASE_ADDR        = 4'h4,
    parameter SLV5_BASE_LSB         = 28,
    parameter SLV5_BASE_ADDR        = 4'h5,
    parameter SLV6_BASE_LSB         = 28,
    parameter SLV6_BASE_ADDR        = 4'h6,
    parameter SLV7_BASE_LSB         = 28,
    parameter SLV7_BASE_ADDR        = 4'h7
)
(
    input                           clk,
    input                           rst_n,

    // Device enabling.
    input  [7:0]                    slv_dev_vld,

    // Master.
    input                           mst_req_vld,
    output                          mst_req_rdy,
    input                           mst_req_read,
    input  [ALEN-1:0]               mst_req_addr,
    input  [MLEN-1:0]               mst_req_mask,
    input  [DLEN-1:0]               mst_req_data,
    output                          mst_rsp_vld,
    input                           mst_rsp_rdy,
    output [1:0]                    mst_rsp_excp,
    output [DLEN-1:0]               mst_rsp_data,

    // Slaves.
    output                          slv0_req_vld,
    input                           slv0_req_rdy,
    output                          slv0_req_read,
    output [ALEN-1:0]               slv0_req_addr,
    output [MLEN-1:0]               slv0_req_mask,
    output [DLEN-1:0]               slv0_req_data,
    input                           slv0_rsp_vld,
    output                          slv0_rsp_rdy,
    input  [1:0]                    slv0_rsp_excp,
    input  [DLEN-1:0]               slv0_rsp_data,

    output                          slv1_req_vld,
    input                           slv1_req_rdy,
    output                          slv1_req_read,
    output [ALEN-1:0]               slv1_req_addr,
    output [MLEN-1:0]               slv1_req_mask,
    output [DLEN-1:0]               slv1_req_data,
    input                           slv1_rsp_vld,
    output                          slv1_rsp_rdy,
    input  [1:0]                    slv1_rsp_excp,
    input  [DLEN-1:0]               slv1_rsp_data,

    output                          slv2_req_vld,
    input                           slv2_req_rdy,
    output                          slv2_req_read,
    output [ALEN-1:0]               slv2_req_addr,
    output [MLEN-1:0]               slv2_req_mask,
    output [DLEN-1:0]               slv2_req_data,
    input                           slv2_rsp_vld,
    output                          slv2_rsp_rdy,
    input  [1:0]                    slv2_rsp_excp,
    input  [DLEN-1:0]               slv2_rsp_data,

    output                          slv3_req_vld,
    input                           slv3_req_rdy,
    output                          slv3_req_read,
    output [ALEN-1:0]               slv3_req_addr,
    output [MLEN-1:0]               slv3_req_mask,
    output [DLEN-1:0]               slv3_req_data,
    input                           slv3_rsp_vld,
    output                          slv3_rsp_rdy,
    input  [1:0]                    slv3_rsp_excp,
    input  [DLEN-1:0]               slv3_rsp_data,

    output                          slv4_req_vld,
    input                           slv4_req_rdy,
    output                          slv4_req_read,
    output [ALEN-1:0]               slv4_req_addr,
    output [MLEN-1:0]               slv4_req_mask,
    output [DLEN-1:0]               slv4_req_data,
    input                           slv4_rsp_vld,
    output                          slv4_rsp_rdy,
    input  [1:0]                    slv4_rsp_excp,
    input  [DLEN-1:0]               slv4_rsp_data,

    output                          slv5_req_vld,
    input                           slv5_req_rdy,
    output                          slv5_req_read,
    output [ALEN-1:0]               slv5_req_addr,
    output [MLEN-1:0]               slv5_req_mask,
    output [DLEN-1:0]               slv5_req_data,
    input                           slv5_rsp_vld,
    output                          slv5_rsp_rdy,
    input  [1:0]                    slv5_rsp_excp,
    input  [DLEN-1:0]               slv5_rsp_data,

    output                          slv6_req_vld,
    input                           slv6_req_rdy,
    output                          slv6_req_read,
    output [ALEN-1:0]               slv6_req_addr,
    output [MLEN-1:0]               slv6_req_mask,
    output [DLEN-1:0]               slv6_req_data,
    input                           slv6_rsp_vld,
    output                          slv6_rsp_rdy,
    input  [1:0]                    slv6_rsp_excp,
    input  [DLEN-1:0]               slv6_rsp_data,

    output                          slv7_req_vld,
    input                           slv7_req_rdy,
    output                          slv7_req_read,
    output [ALEN-1:0]               slv7_req_addr,
    output [MLEN-1:0]               slv7_req_mask,
    output [DLEN-1:0]               slv7_req_data,
    input                           slv7_rsp_vld,
    output                          slv7_rsp_rdy,
    input  [1:0]                    slv7_rsp_excp,
    input  [DLEN-1:0]               slv7_rsp_data
);

    localparam MST_PORT_NUM         = 1;
    localparam SLV_PORT_NUM         = 8;

    wire                            mst_dev_vld;

    // 1D slave ports.
    wire [SLV_PORT_NUM-1:0]         slv_req_vld;
    wire [SLV_PORT_NUM-1:0]         slv_req_rdy;
    wire [SLV_PORT_NUM-1:0]         slv_req_read;
    wire [SLV_PORT_NUM*ALEN-1:0]    slv_req_addr;
    wire [SLV_PORT_NUM*MLEN-1:0]    slv_req_mask;
    wire [SLV_PORT_NUM*DLEN-1:0]    slv_req_data;
    wire [SLV_PORT_NUM-1:0]         slv_rsp_vld;
    wire [SLV_PORT_NUM-1:0]         slv_rsp_rdy;
    wire [SLV_PORT_NUM*2-1:0]       slv_rsp_excp;
    wire [SLV_PORT_NUM*DLEN-1:0]    slv_rsp_data;

    assign mst_dev_vld              = 1'b1;

    assign slv_req_rdy  = {slv7_req_rdy , slv6_req_rdy , slv5_req_rdy , slv4_req_rdy , slv3_req_rdy , slv2_req_rdy , slv1_req_rdy , slv0_req_rdy };
    assign slv_rsp_vld  = {slv7_rsp_vld , slv6_rsp_vld , slv5_rsp_vld , slv4_rsp_vld , slv3_rsp_vld , slv2_rsp_vld , slv1_rsp_vld , slv0_rsp_vld };
    assign slv_rsp_excp = {slv7_rsp_excp, slv6_rsp_excp, slv5_rsp_excp, slv4_rsp_excp, slv3_rsp_excp, slv2_rsp_excp, slv1_rsp_excp, slv0_rsp_excp};
    assign slv_rsp_data = {slv7_rsp_data, slv6_rsp_data, slv5_rsp_data, slv4_rsp_data, slv3_rsp_data, slv2_rsp_data, slv1_rsp_data, slv0_rsp_data};
    assign {slv7_req_vld , slv6_req_vld , slv5_req_vld , slv4_req_vld , slv3_req_vld , slv2_req_vld , slv1_req_vld , slv0_req_vld } = slv_req_vld ;
    assign {slv7_req_read, slv6_req_read, slv5_req_read, slv4_req_read, slv3_req_read, slv2_req_read, slv1_req_read, slv0_req_read} = slv_req_read;
    assign {slv7_req_addr, slv6_req_addr, slv5_req_addr, slv4_req_addr, slv3_req_addr, slv2_req_addr, slv1_req_addr, slv0_req_addr} = slv_req_addr;
    assign {slv7_req_mask, slv6_req_mask, slv5_req_mask, slv4_req_mask, slv3_req_mask, slv2_req_mask, slv1_req_mask, slv0_req_mask} = slv_req_mask;
    assign {slv7_req_data, slv6_req_data, slv5_req_data, slv4_req_data, slv3_req_data, slv2_req_data, slv1_req_data, slv0_req_data} = slv_req_data;
    assign {slv7_rsp_rdy , slv6_rsp_rdy , slv5_rsp_rdy , slv4_rsp_rdy , slv3_rsp_rdy , slv2_rsp_rdy , slv1_rsp_rdy , slv0_rsp_rdy } = slv_rsp_rdy ;

    uv_bus_fab
    #(
        .ALEN                       ( ALEN              ),
        .DLEN                       ( DLEN              ),
        .MLEN                       ( MLEN              ),
        .PIPE_STAGE                 ( PIPE_STAGE        ),
        .MST_PORT_NUM               ( MST_PORT_NUM      ),
        .SLV_PORT_NUM               ( SLV_PORT_NUM      ),
        .SLV0_BASE_LSB              ( SLV0_BASE_LSB     ),
        .SLV0_BASE_ADDR             ( SLV0_BASE_ADDR    ),
        .SLV1_BASE_LSB              ( SLV1_BASE_LSB     ),
        .SLV1_BASE_ADDR             ( SLV1_BASE_ADDR    ),
        .SLV2_BASE_LSB              ( SLV2_BASE_LSB     ),
        .SLV2_BASE_ADDR             ( SLV2_BASE_ADDR    ),
        .SLV3_BASE_LSB              ( SLV3_BASE_LSB     ),
        .SLV3_BASE_ADDR             ( SLV3_BASE_ADDR    ),
        .SLV4_BASE_LSB              ( SLV4_BASE_LSB     ),
        .SLV4_BASE_ADDR             ( SLV4_BASE_ADDR    ),
        .SLV5_BASE_LSB              ( SLV5_BASE_LSB     ),
        .SLV5_BASE_ADDR             ( SLV5_BASE_ADDR    ),
        .SLV6_BASE_LSB              ( SLV6_BASE_LSB     ),
        .SLV6_BASE_ADDR             ( SLV6_BASE_ADDR    ),
        .SLV7_BASE_LSB              ( SLV7_BASE_LSB     ),
        .SLV7_BASE_ADDR             ( SLV7_BASE_ADDR    )
    )
    u_bus_fab_gnrl
    (
        .clk                        ( clk               ),
        .rst_n                      ( rst_n             ),

        // Masters.
        .mst_dev_vld                ( mst_dev_vld       ),
        .mst_req_vld                ( mst_req_vld       ),
        .mst_req_rdy                ( mst_req_rdy       ),
        .mst_req_read               ( mst_req_read      ),
        .mst_req_addr               ( mst_req_addr      ),
        .mst_req_mask               ( mst_req_mask      ),
        .mst_req_data               ( mst_req_data      ),
        .mst_rsp_vld                ( mst_rsp_vld       ),
        .mst_rsp_rdy                ( mst_rsp_rdy       ),
        .mst_rsp_excp               ( mst_rsp_excp      ),
        .mst_rsp_data               ( mst_rsp_data      ),

        // Slaves.
        .slv_dev_vld                ( slv_dev_vld       ),
        .slv_req_vld                ( slv_req_vld       ),
        .slv_req_rdy                ( slv_req_rdy       ),
        .slv_req_read               ( slv_req_read      ),
        .slv_req_addr               ( slv_req_addr      ),
        .slv_req_mask               ( slv_req_mask      ),
        .slv_req_data               ( slv_req_data      ),
        .slv_rsp_vld                ( slv_rsp_vld       ),
        .slv_rsp_rdy                ( slv_rsp_rdy       ),
        .slv_rsp_excp               ( slv_rsp_excp      ),
        .slv_rsp_data               ( slv_rsp_data      )
    );

endmodule
