../../../design/sys/uv_sys.v
../../../design/sys/uv_mem_subsys.v
../../../design/sys/uv_dev_subsys.v
../../../design/sys/uv_perip_subsys.v

../../../design/core/uv_core.v
../../../design/core/uv_ucore.v
../../../design/core/uv_ifu.v
../../../design/core/uv_bpu.v
../../../design/core/uv_idu.v
../../../design/core/uv_exu.v
../../../design/core/uv_lsu.v
../../../design/core/uv_cmt.v
../../../design/core/uv_csr.v
../../../design/core/uv_alu.v
../../../design/core/uv_mul.v
../../../design/core/uv_div.v
../../../design/core/uv_regfile.v
../../../design/core/uv_biu.v

../../../design/mem/uv_rom.v
../../../design/mem/uv_rom_logic.v
../../../design/mem/uv_dam.v
../../../design/mem/uv_sram_bus_ctrl.v
../../../design/mem/uv_sram_sp.v
../../../design/mem/uv_dev_sram.v
../../../design/mem/uv_eflash.v
../../../design/mem/uv_queue.v

../../../design/dev/uv_slc.v
../../../design/dev/uv_tmr.v
../../../design/dev/uv_tmr_apb.v
../../../design/dev/uv_wdt.v
../../../design/dev/uv_wdt_apb.v
../../../design/dev/uv_spi.v
../../../design/dev/uv_spi_apb.v
../../../design/dev/uv_spi_reg.v
../../../design/dev/uv_spi_rtx.v
../../../design/dev/uv_i2c.v
../../../design/dev/uv_i2c_apb.v
../../../design/dev/uv_i2c_reg.v
../../../design/dev/uv_i2c_rtx.v
../../../design/dev/uv_uart.v
../../../design/dev/uv_uart_apb.v
../../../design/dev/uv_uart_reg.v
../../../design/dev/uv_uart_tx.v
../../../design/dev/uv_uart_rx.v
../../../design/dev/uv_gpio.v
../../../design/dev/uv_gpio_apb.v
../../../design/dev/uv_iomux.v
../../../design/dev/uv_dbg.v

../../../design/bus/uv_bus_fab.v
../../../design/bus/uv_bus_fab_1x2.v
../../../design/bus/uv_bus_fab_1x8.v
../../../design/bus/uv_bus_fab_2x2.v
../../../design/bus/uv_bus_fab_4x4.v
../../../design/bus/uv_bus_fab_4x8.v
../../../design/bus/uv_bus_to_apb.v

../../../design/misc/uv_arb_rr.v
../../../design/misc/uv_arb_fp.v
../../../design/misc/uv_clk_gate.v
../../../design/misc/uv_rst_sync.v
../../../design/misc/uv_sync.v
../../../design/misc/uv_pipe.v
