# See LICENSE for license details.

# External Clock.
# create_clock -period 10 [get_ports io_ext_clk]

# I/O Constraints.
set_property PACKAGE_PIN AB11 [get_ports io_ext_clk]
set_property PACKAGE_PIN W9 [get_ports io_btn_rst_n]

set_property PACKAGE_PIN G24 [get_ports {io_gpio[0]}]
set_property PACKAGE_PIN F24 [get_ports {io_gpio[1]}]
set_property PACKAGE_PIN G22 [get_ports {io_gpio[2]}]
set_property PACKAGE_PIN F23 [get_ports {io_gpio[3]}]
set_property PACKAGE_PIN F22 [get_ports {io_gpio[4]}]
set_property PACKAGE_PIN E23 [get_ports {io_gpio[5]}]
set_property PACKAGE_PIN D23 [get_ports {io_gpio[6]}]
set_property PACKAGE_PIN D24 [get_ports {io_gpio[7]}]
set_property PACKAGE_PIN K18 [get_ports {io_gpio[8]}]
set_property PACKAGE_PIN L17 [get_ports {io_gpio[9]}]
set_property PACKAGE_PIN L18 [get_ports {io_gpio[10]}]
set_property PACKAGE_PIN M17 [get_ports {io_gpio[11]}]
set_property PACKAGE_PIN K17 [get_ports {io_gpio[12]}]
set_property PACKAGE_PIN K16 [get_ports {io_gpio[13]}]
set_property PACKAGE_PIN L20 [get_ports {io_gpio[14]}]
set_property PACKAGE_PIN L19 [get_ports {io_gpio[15]}]
set_property PACKAGE_PIN C21 [get_ports {io_gpio[16]}]
set_property PACKAGE_PIN B21 [get_ports {io_gpio[17]}]
set_property PACKAGE_PIN E21 [get_ports {io_gpio[18]}]
set_property PACKAGE_PIN E22 [get_ports {io_gpio[19]}]
set_property PACKAGE_PIN B20 [get_ports {io_gpio[20]}]
set_property PACKAGE_PIN A20 [get_ports {io_gpio[21]}]
set_property PACKAGE_PIN D21 [get_ports {io_gpio[22]}]
set_property PACKAGE_PIN C22 [get_ports {io_gpio[23]}]
set_property PACKAGE_PIN J19 [get_ports {io_gpio[24]}]
set_property PACKAGE_PIN J18 [get_ports {io_gpio[25]}]
set_property PACKAGE_PIN J20 [get_ports {io_gpio[26]}]
set_property PACKAGE_PIN K20 [get_ports {io_gpio[27]}]
set_property PACKAGE_PIN G20 [get_ports {io_gpio[28]}]
set_property PACKAGE_PIN H19 [get_ports {io_gpio[29]}]
set_property PACKAGE_PIN E20 [get_ports {io_gpio[30]}]
set_property PACKAGE_PIN F19 [get_ports {io_gpio[31]}]

set_property IOSTANDARD LVCMOS18 [get_ports io_ext_clk]
set_property IOSTANDARD LVCMOS18 [get_ports io_btn_rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {io_gpio[31]}]
